% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% https://github.com/rstudio/rmarkdown/issues/337
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

% https://github.com/rstudio/rmarkdown/pull/252
\usepackage{titling}
\setlength{\droptitle}{-2em}

\pretitle{\vspace{\droptitle}\centering\huge}
\posttitle{\par}

\preauthor{\centering\large\emph}
\postauthor{\par}

\predate{\centering\large\emph}
\postdate{\par}

\date{}

\begin{document}

\hypertarget{practice-assignment}{%
\section{Practice Assignment}\label{practice-assignment}}

The goal of this assignment is to provide a ``bridge'' between the first
two weeks of lectures and assignment 1 for those either new to R or
struggling with how to approach the assignment.

This guided example, will \textbf{not} provide a solution for
programming assignment 1. However, it will guide you through some core
concepts and give you some practical experience to hopefully make
assignment 1 seems less daunting.

To begin, download this file and unzip it into your R working
directory.\\
\url{http://s3.amazonaws.com/practice_assignment/diet_data.zip}

You can do this in R with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dataset_url <-}\StringTok{ "http://s3.amazonaws.com/practice_assignment/diet_data.zip"}
\KeywordTok{download.file}\NormalTok{(dataset_url, }\StringTok{"diet_data.zip"}\NormalTok{)}
\KeywordTok{unzip}\NormalTok{(}\StringTok{"diet_data.zip"}\NormalTok{, }\DataTypeTok{exdir =} \StringTok{"diet_data"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If you're not sure where your working directory is, you can find out
with the \texttt{getwd()} command. Alternatively, you can view/change it
through the Tools \textgreater{} Global Options menu in R Studio.

So assuming you've unzipped the file into your R directory, you should
have a folder called diet\_data. In that folder there are five files.
Let's get a list of those files:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{list.files}\NormalTok{(}\StringTok{"diet_data"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Andy.csv"  "David.csv" "John.csv"  "Mike.csv"  "Steve.csv"
\end{verbatim}

Okay, so we have 5 files. Let's take a look at one to see what's inside:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"diet_data/Andy.csv"}\NormalTok{)}
\KeywordTok{head}\NormalTok{(andy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Patient.Name Age Weight Day
## 1         Andy  30    140   1
## 2         Andy  30    140   2
## 3         Andy  30    140   3
## 4         Andy  30    139   4
## 5         Andy  30    138   5
## 6         Andy  30    138   6
\end{verbatim}

It appears that the file has 4 columns, Patient.Name, Age, Weight, and
Day. Let's figure out how many rows there are by looking at the length
of the `Day' column:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(andy}\OperatorTok{$}\NormalTok{Day)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30
\end{verbatim}

30 rows. OK.

Alternatively, you could look at the dimensions of the data.frame:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(andy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30  4
\end{verbatim}

This tells us that we 30 rows of data in 4 columns. There are some other
commands we might want to run to get a feel for a new data file,
\texttt{str()}, \texttt{summary()}, and \texttt{names()}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(andy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  4 variables:
##  $ Patient.Name: Factor w/ 1 level "Andy": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age         : int  30 30 30 30 30 30 30 30 30 30 ...
##  $ Weight      : int  140 140 140 139 138 138 138 138 138 138 ...
##  $ Day         : int  1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(andy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Patient.Name      Age         Weight           Day       
##  Andy:30      Min.   :30   Min.   :135.0   Min.   : 1.00  
##               1st Qu.:30   1st Qu.:137.0   1st Qu.: 8.25  
##               Median :30   Median :137.5   Median :15.50  
##               Mean   :30   Mean   :137.3   Mean   :15.50  
##               3rd Qu.:30   3rd Qu.:138.0   3rd Qu.:22.75  
##               Max.   :30   Max.   :140.0   Max.   :30.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(andy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Patient.Name" "Age"          "Weight"       "Day"
\end{verbatim}

So we have 30 days of data. To save you time, all of the other files
match this format and length. I've made up 30 days worth of weight data
for 5 subjects of an imaginary diet study.

Let's play around with a couple of concepts. First, how would we see
Andy's starting weight? We want to subset the data. Specifically, the
first row of the `Weight' column:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy[}\DecValTok{1}\NormalTok{, }\StringTok{"Weight"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 140
\end{verbatim}

We can do the same thing to find his final weight on Day 30:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy[}\DecValTok{30}\NormalTok{, }\StringTok{"Weight"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 135
\end{verbatim}

Alternatively, you could create a subset of the `Weight' column where
the data where `Day' is equal to 30.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy[}\KeywordTok{which}\NormalTok{(andy}\OperatorTok{$}\NormalTok{Day }\OperatorTok{==}\StringTok{ }\DecValTok{30}\NormalTok{), }\StringTok{"Weight"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 135
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy[}\KeywordTok{which}\NormalTok{(andy[,}\StringTok{"Day"}\NormalTok{] }\OperatorTok{==}\StringTok{ }\DecValTok{30}\NormalTok{), }\StringTok{"Weight"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 135
\end{verbatim}

Or, we could use the \texttt{subset()} function to do the same thing:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{subset}\NormalTok{(andy}\OperatorTok{$}\NormalTok{Weight, andy}\OperatorTok{$}\NormalTok{Day}\OperatorTok{==}\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 135
\end{verbatim}

There are lots of ways to get from A to B when using R. However it's
important to understand some of the various approaches to subsetting
data.

Let's assign Andy's starting and ending weight to vectors:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy_start <-}\StringTok{ }\NormalTok{andy[}\DecValTok{1}\NormalTok{, }\StringTok{"Weight"}\NormalTok{]}
\NormalTok{andy_end <-}\StringTok{ }\NormalTok{andy[}\DecValTok{30}\NormalTok{, }\StringTok{"Weight"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

We can find out how much weight he lost by subtracting the vectors:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy_loss <-}\StringTok{ }\NormalTok{andy_start }\OperatorTok{-}\StringTok{ }\NormalTok{andy_end}
\NormalTok{andy_loss}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

Andy lost 5 pounds over the 30 days. Not bad. What if we want to look at
other subjects or maybe even everybody at once?

Let's look back to the \texttt{list.files()} command. It returns the
contents of a directory in alphabetical order. You can type
\texttt{?list.files} at the R prompt to learn more about the function.

Let's take the output of \texttt{list.files()} and store it:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files <-}\StringTok{ }\KeywordTok{list.files}\NormalTok{(}\StringTok{"diet_data"}\NormalTok{)}
\NormalTok{files}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Andy.csv"  "David.csv" "John.csv"  "Mike.csv"  "Steve.csv"
\end{verbatim}

Knowing that `files' is now a list of the contents of `diet\_data' in
alphabetical order, we can call a specific file by subsetting it:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Andy.csv"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files[}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "David.csv"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files[}\DecValTok{3}\OperatorTok{:}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "John.csv"  "Mike.csv"  "Steve.csv"
\end{verbatim}

Let's take a quick look at John.csv:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(}\KeywordTok{read.csv}\NormalTok{(files[}\DecValTok{3}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in file(file, "rt"): cannot open file 'John.csv': No such file or
## directory
\end{verbatim}

\begin{verbatim}
## Error in file(file, "rt"): cannot open the connection
\end{verbatim}

Woah, what happened? Well, John.csv is sitting inside the diet\_data
folder. We just tried to run the equivalent of
\texttt{read.csv("John.csv")} and R correctly told us that there isn't a
file called John.csv in our working directory. To fix this, we need to
append the directory to the beginning of the file name.

One approach would be to use \texttt{paste()} or \texttt{sprintf()}.
However, if you go back to the help file for \texttt{list.files()},
you'll see that there is an argument called \texttt{full.names} that
will append (technically prepend) the path to the file name for us.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files_full <-}\StringTok{ }\KeywordTok{list.files}\NormalTok{(}\StringTok{"diet_data"}\NormalTok{, }\DataTypeTok{full.names=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{files_full}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "diet_data/Andy.csv"  "diet_data/David.csv" "diet_data/John.csv" 
## [4] "diet_data/Mike.csv"  "diet_data/Steve.csv"
\end{verbatim}

Pretty cool. Now let's try taking a look at John.csv again:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(}\KeywordTok{read.csv}\NormalTok{(files_full[}\DecValTok{3}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Patient.Name Age Weight Day
## 1         John  22    175   1
## 2         John  22    175   2
## 3         John  22    175   3
## 4         John  22    175   4
## 5         John  22    175   5
## 6         John  22    175   6
\end{verbatim}

Success! So what if we wanted to create one big data frame with
everybody's data in it? We'd do that with rbind and a loop. Let's start
with rbind:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{andy_david <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(andy, }\KeywordTok{read.csv}\NormalTok{(files_full[}\DecValTok{2}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

This line of code took our existing data frame, Andy, and added the rows
from David.csv to the end of it. We can check this with:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(andy_david)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Patient.Name Age Weight Day
## 1         Andy  30    140   1
## 2         Andy  30    140   2
## 3         Andy  30    140   3
## 4         Andy  30    139   4
## 5         Andy  30    138   5
## 6         Andy  30    138   6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{tail}\NormalTok{(andy_david)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Patient.Name Age Weight Day
## 55        David  35    203  25
## 56        David  35    203  26
## 57        David  35    202  27
## 58        David  35    202  28
## 59        David  35    202  29
## 60        David  35    201  30
\end{verbatim}

One thing to note, rbind needs 2 arguments. The first is an existing
data frame and the second is what you want to append to it. This means
that there are occassions when you might want to create an empty data
frame just so there's \emph{something} to use as the existing data frame
in the rbind argument.

Don't worry if you can't imagine when that would be useful because
you'll see an example in just a little while.

Now, let's create a subset of the data frame that shows us just the 25th
day for Andy and David.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{day_}\DecValTok{25}\NormalTok{ <-}\StringTok{ }\NormalTok{andy_david[}\KeywordTok{which}\NormalTok{(andy_david}\OperatorTok{$}\NormalTok{Day }\OperatorTok{==}\StringTok{ }\DecValTok{25}\NormalTok{), ]}
\NormalTok{day_}\DecValTok{25}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Patient.Name Age Weight Day
## 25         Andy  30    135  25
## 55        David  35    203  25
\end{verbatim}

Now you could manually go through and append everybody's data to the
same data frame using rbind, but that's not a practical solution if
you've got lots and lots of files. So let's try using a loop.

To understand what's happening in a loop, let's try something:

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{) \{}\KeywordTok{print}\NormalTok{(i)\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
## [1] 2
## [1] 3
## [1] 4
## [1] 5
\end{verbatim}

As you can see, for each pass through the loop, i increases by 1 from 1
through 5. Let's apply that concept to our list of files.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{) \{}
\NormalTok{        dat <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(dat, }\KeywordTok{read.csv}\NormalTok{(files_full[i]))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Error in rbind(dat, read.csv(files_full[i])): object 'dat' not found
\end{verbatim}

Whoops. Object `dat' not found. This is because you can't rbind
something into a file that doesn't exist yet. So let's create an empty
data frame called `dat' before running the loop.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{) \{}
\NormalTok{        dat <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(dat, }\KeywordTok{read.csv}\NormalTok{(files_full[i]))}
\NormalTok{\}}
\KeywordTok{str}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    150 obs. of  4 variables:
##  $ Patient.Name: Factor w/ 5 levels "Andy","David",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age         : int  30 30 30 30 30 30 30 30 30 30 ...
##  $ Weight      : int  140 140 140 139 138 138 138 138 138 138 ...
##  $ Day         : int  1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

Cool. We now have a data frame called `dat' with all of our data in it.
Out of curiousity, what would happen if we had put
\texttt{dat\ \textless{}-\ data.frame()} inside of the loop? Let's see:

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{) \{}
\NormalTok{        dat2 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{()}
\NormalTok{        dat2 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(dat2, }\KeywordTok{read.csv}\NormalTok{(files_full[i]))}
\NormalTok{\}}
\KeywordTok{str}\NormalTok{(dat2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  4 variables:
##  $ Patient.Name: Factor w/ 1 level "Steve": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age         : int  55 55 55 55 55 55 55 55 55 55 ...
##  $ Weight      : int  225 225 225 224 224 224 223 223 223 223 ...
##  $ Day         : int  1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(dat2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Patient.Name Age Weight Day
## 1        Steve  55    225   1
## 2        Steve  55    225   2
## 3        Steve  55    225   3
## 4        Steve  55    224   4
## 5        Steve  55    224   5
## 6        Steve  55    224   6
\end{verbatim}

Because we put \texttt{dat2\ \textless{}-\ data.frame()} inside of the
loop, \texttt{dat2} is being rewritten with each pass of the loop. So we
only end up with the data from the last file in our list.

Back to \texttt{dat}\ldots{} So what if we wanted to know the median
weight for all the data? Let's use the \texttt{median()} function.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(dat}\OperatorTok{$}\NormalTok{Weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NA
\end{verbatim}

NA? Why did that happen? Type `dat' into the console and you'll see a
print out of all 150 obversations. Scroll back up to row 77, and you'll
see that we have some missing data from John, which is recorded as NA by
R.

We need to get rid of those NA's for the purposes of calculating the
median. There are several approaches. For instance, we could subset the
data using \texttt{complete.cases()} or \texttt{is.na()}. But if you
look at \texttt{?median}, you'll see there is an argument called
\texttt{na.rm} that will strip the NA values out for us.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(dat}\OperatorTok{$}\NormalTok{Weight, }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 190
\end{verbatim}

So 190 is the median weight. We can find the median weight of day 30 by
taking the median of a subset of the data where Day=30.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat_}\DecValTok{30}\NormalTok{ <-}\StringTok{ }\NormalTok{dat[}\KeywordTok{which}\NormalTok{(dat[, }\StringTok{"Day"}\NormalTok{] }\OperatorTok{==}\StringTok{ }\DecValTok{30}\NormalTok{),]}
\NormalTok{dat_}\DecValTok{30}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Patient.Name Age Weight Day
## 30          Andy  30    135  30
## 60         David  35    201  30
## 90          John  22    177  30
## 120         Mike  40    192  30
## 150        Steve  55    214  30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(dat_}\DecValTok{30}\OperatorTok{$}\NormalTok{Weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 192
\end{verbatim}

We've done a lot of manual data manipulation so far. Let's build a
function that will return the median weight of a given day.

Let's start out by defining what the arguments of the function should
be. These are the parameters that the user will define. The first
parameter the user will need to define is the directory that is holding
the data. The second parameter they need to define is the day for which
they want to calculate the median.

So our function is going to start out something like this:

\texttt{weightmedian\ \textless{}-\ function(directory,\ day)\ \ \{\ \ \ \ \ \ \ \ \ \#\ content\ of\ the\ function\ \}}

So what goes in the content? Let's think through it logically. We need a
data frame with all of the data from the CSV's. We'll then subset that
data frame using the argument \texttt{day} and take the median of that
subset.

In order to get all of the data into a single data frame, we can use the
method we worked through earlier using \texttt{list.files()} and
\texttt{rbind()}.

Essentially, these are all things that we've done in this example. Now
we just need to combine them into a single function.

So what does the function look like?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{weightmedian <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(directory, day)  \{}
\NormalTok{        files_list <-}\StringTok{ }\KeywordTok{list.files}\NormalTok{(directory, }\DataTypeTok{full.names=}\OtherTok{TRUE}\NormalTok{)   }\CommentTok{#creates a list of files}
\NormalTok{        dat <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{()                             }\CommentTok{#creates an empty data frame}
        \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{) \{                                }
                \CommentTok{#loops through the files, rbinding them together }
\NormalTok{                dat <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(dat, }\KeywordTok{read.csv}\NormalTok{(files_list[i]))}
\NormalTok{        \}}
\NormalTok{        dat_subset <-}\StringTok{ }\NormalTok{dat[}\KeywordTok{which}\NormalTok{(dat[, }\StringTok{"Day"}\NormalTok{] }\OperatorTok{==}\StringTok{ }\NormalTok{day),]  }\CommentTok{#subsets the rows that match the 'day' argument}
        \KeywordTok{median}\NormalTok{(dat_subset[, }\StringTok{"Weight"}\NormalTok{], }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{)      }\CommentTok{#identifies the median weight }
                                                        \CommentTok{#while stripping out the NAs}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

You can test this function by running it a few different times:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{weightmedian}\NormalTok{(}\DataTypeTok{directory =} \StringTok{"diet_data"}\NormalTok{, }\DataTypeTok{day =} \DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 197.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{weightmedian}\NormalTok{(}\StringTok{"diet_data"}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 188
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{weightmedian}\NormalTok{(}\StringTok{"diet_data"}\NormalTok{, }\DecValTok{17}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 198
\end{verbatim}

Hopefully, this has given you some practice applying the basic concepts
from weeks 1 and 2. If you can work your way through this example, you
should have all of the tools needed to complete part 1 of assignment 1.
Parts 2 and 3 are really just expanding on the same basic concepts,
potentially adding in some ideas like cbinds and if-else.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

One last quick note: The approach I'm showing above for building the
data frame is submoptimal. It works, but generally speaking, you don't
want to build data frames or vectors by copying and re-copying them
inside of a loop. If you've got a lot of data it can become very, very
slow. However, this tutorial is meant to provide an introduction to
these concepts, and you can use this approach successfully for
programming assignments 1 and 3.

If you're interested in learning the better approach, check out Hadley
Wickam's excellent material on functionals within R:
\url{http://adv-r.had.co.nz/Functionals.html}. But if you're new to both
programming and R, I would skip it for now as it will just confuse you.
Come back and revisit it (and the rest of this section) once you are
able to write working functions using the approach above.

However, for those of you that do want to see a better way to create a
dataframe\ldots.

The main issue with the approach above is growing an object inside of
loop by copying and recopying it. It works, but it's slow and if you've
got a lot of data, it will probably cause issues. The better approach is
to create an output object of an appropriate size and then fill it up.

So the first thing we do is create an empty list that's the length of
our expected output. In this case, our input object is going to be
\texttt{files\_full} and our empty list is going to be \texttt{tmp}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(files_full)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Length     Class      Mode 
##         5 character character
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tmp <-}\StringTok{ }\KeywordTok{vector}\NormalTok{(}\DataTypeTok{mode =} \StringTok{"list"}\NormalTok{, }\DataTypeTok{length =} \KeywordTok{length}\NormalTok{(files_full))}
\KeywordTok{summary}\NormalTok{(tmp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Length Class  Mode
## [1,] 0      -none- NULL
## [2,] 0      -none- NULL
## [3,] 0      -none- NULL
## [4,] 0      -none- NULL
## [5,] 0      -none- NULL
\end{verbatim}

Now we need to read in those csv files and drop them into \texttt{tmp}.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \KeywordTok{seq_along}\NormalTok{(files_full)) \{}
\NormalTok{        tmp[[i]] <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(files_full[[i]])}
\NormalTok{\}}
\KeywordTok{str}\NormalTok{(tmp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 5
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "Andy": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 30 30 30 30 30 30 30 30 30 30 ...
##   ..$ Weight      : int [1:30] 140 140 140 139 138 138 138 138 138 138 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "David": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 35 35 35 35 35 35 35 35 35 35 ...
##   ..$ Weight      : int [1:30] 210 209 209 209 209 209 209 208 208 208 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "John": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 22 22 22 22 22 22 22 22 22 22 ...
##   ..$ Weight      : int [1:30] 175 175 175 175 175 175 175 175 175 175 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "Mike": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 40 40 40 40 40 40 40 40 40 40 ...
##   ..$ Weight      : int [1:30] 188 188 188 188 189 189 189 189 189 189 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "Steve": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 55 55 55 55 55 55 55 55 55 55 ...
##   ..$ Weight      : int [1:30] 225 225 225 224 224 224 223 223 223 223 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

What we just did was read in each of the csv files and place them inside
of our list. Now we have a list of 5 elements called \texttt{tmp}, where
each element of the list is a data frame containing one of the csv
files. It just so happens that what we just did is functionally
identical to using \texttt{lapply}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(}\KeywordTok{lapply}\NormalTok{(files_full, read.csv))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 5
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "Andy": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 30 30 30 30 30 30 30 30 30 30 ...
##   ..$ Weight      : int [1:30] 140 140 140 139 138 138 138 138 138 138 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "David": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 35 35 35 35 35 35 35 35 35 35 ...
##   ..$ Weight      : int [1:30] 210 209 209 209 209 209 209 208 208 208 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "John": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 22 22 22 22 22 22 22 22 22 22 ...
##   ..$ Weight      : int [1:30] 175 175 175 175 175 175 175 175 175 175 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "Mike": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 40 40 40 40 40 40 40 40 40 40 ...
##   ..$ Weight      : int [1:30] 188 188 188 188 189 189 189 189 189 189 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :'data.frame':    30 obs. of  4 variables:
##   ..$ Patient.Name: Factor w/ 1 level "Steve": 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ Age         : int [1:30] 55 55 55 55 55 55 55 55 55 55 ...
##   ..$ Weight      : int [1:30] 225 225 225 224 224 224 223 223 223 223 ...
##   ..$ Day         : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

This is part of the power of the apply family of functions. You don't
have to worry about the ``housekeeping'' of looping, and instead you can
focus on the function you're using. When you or somebody else comes back
weeks later and reads through your code, it's easier to understand what
you were doing and why. If somebody says that the apply functions are
more ``expressive'', this is what they mean.

Now we still need to go from a list to a single data frame, although you
\emph{can} manipulate the data within this structure:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(tmp[[}\DecValTok{1}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  4 variables:
##  $ Patient.Name: Factor w/ 1 level "Andy": 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age         : int  30 30 30 30 30 30 30 30 30 30 ...
##  $ Weight      : int  140 140 140 139 138 138 138 138 138 138 ...
##  $ Day         : int  1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(tmp[[}\DecValTok{1}\NormalTok{]][,}\StringTok{"Day"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 2 3 4 5 6
\end{verbatim}

We can use a function called \texttt{do.call()} to combine \texttt{tmp}
into a single data frame. \texttt{do.call} lets you specify a function
and then passes a list as if each element of the list were an argument
to the function. The syntax is
\texttt{do.call(function\_you\_want\_to\_use,\ list\_of\_arguments)}. In
our case, we want to \texttt{rbind()} our list of data frames,
\texttt{tmp}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{output <-}\StringTok{ }\KeywordTok{do.call}\NormalTok{(rbind, tmp)}
\KeywordTok{str}\NormalTok{(output)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    150 obs. of  4 variables:
##  $ Patient.Name: Factor w/ 5 levels "Andy","David",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Age         : int  30 30 30 30 30 30 30 30 30 30 ...
##  $ Weight      : int  140 140 140 139 138 138 138 138 138 138 ...
##  $ Day         : int  1 2 3 4 5 6 7 8 9 10 ...
\end{verbatim}

This approach avoids all of the messy copying and recopying of the data
to build the final data frame. It's much more ``R-like'' and works quite
a bit faster than our other approach.

\end{document}
